### ISSUE TITLE
Docker daemon does not bind to TCP6

### ISSUE THREAD

**Issue by lalalale39** [tamusiunas/docker-coreelec#21]
The service properly only binds to IPv4 ，Running netstat -plnt shows me that the docker-proxy is not listening on IPv6 ports:
CoreELEC:~ # netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      3586/smbd
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      4110/kodi.bin
tcp        0      0 0.0.0.0:9443            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 127.0.0.1:8587          0.0.0.0:*               LISTEN      4110/kodi.bin
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      5131/dockerd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3405/sshd -D [liste
tcp        0      0 0.0.0.0:33783           0.0.0.0:*               LISTEN      3552/rpc.mountd
tcp        0      0 0.0.0.0:36666           0.0.0.0:*               LISTEN      4110/kodi.bin
tcp        0      0 127.0.0.1:47259         0.0.0.0:*               LISTEN      4110/kodi.bin
tcp        0      0 0.0.0.0:48059           0.0.0.0:*               LISTEN      3551/rpc.statd
tcp        0      0 :::9090                 :::*                    LISTEN      4110/kodi.bin
tcp        0      0 :::139                  :::*                    LISTEN      3586/smbd
tcp        0      0 :::111                  :::*                    LISTEN      1/systemd
tcp        0      0 :::8080                 :::*                    LISTEN      4110/kodi.bin
tcp        0      0 :::22                   :::*                    LISTEN      3405/sshd -D [liste
tcp        0      0 :::36666                :::*                    LISTEN      4110/kodi.bin

Google it and find someone said updated docker to 20.10.12 and can fix it. so can you updated this docker ?

**Comment by tamusiunas** [comment]
Updated to docker 20.10.16.
